### ISSUE TITLE
why don't you ever talk like this in class?

### ISSUE THREAD

**Issue by DEFBOIL** [DippreyB/ultidraft#1]
https://github.com/DippreyB/ultidraft/blob/673c478f2601de214542fee71c7e8b24cd6c06a1/backend/server.js#L22
such foul language ☹️

also i need help with
# MAKEBRICKS

sincerely, alexis rivera 2nd period

p.s. i'm only here because i wanted to throw my friend (@IStrikeboomI) under the bus

**Comment by IStrikeboomI** [comment]
im throwing you under

**Comment by IStrikeboomI** [comment]
also i can help with make bricks first what is it
